{% set name = "mtpy-v2" %}
{% set version = "2.0.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mtpy-v2-{{ version }}.tar.gz
  sha256: 28650f05389dd8b4b0a0b2a6a25fc97454a3e81ae715b51b88cba04c9466e22c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
  run:
    - configparser
    - contextily
    - geopandas
    - matplotlib-base
    - mt-metadata
    - mth5
    - numpy
    - pyevtk
    - pyproj
    - python >={{ python_min }}
    - rasterio
    - scipy
    - simpeg >=0.22.0
    - aurora >=0.3.13

test:
  imports:
    - mtpy
    - mtpy.core.mt
    - mtpy.core.mt_collection
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/MTgeophysics/mtpy-v2
  summary: Python toolkit for standard magnetotelluric data processing.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kujaku11
